package fina2.ui.sheet;

import javax.swing.JFrame;
@Deprecated
public class SpreadsheetView extends javax.swing.JFrame {

	private fina2.ui.UIManager ui = fina2.Main.main.ui;
	private fina2.Main main = fina2.Main.main;

	private Spreadsheet sheet;

	/** Creates new SpreadsheetView */
	public SpreadsheetView() {

		try {
			initComponents();
			initSheet();
		} catch (Exception e) {
			e.printStackTrace();
		}

		setExtendedState(JFrame.MAXIMIZED_BOTH);
	}

	/** Inits the sheet */
	private void initSheet() {
		sheet = SpreadsheetsManager.getInstance().createSpreadsheet();
		panel.add(sheet.getComponent(), java.awt.BorderLayout.CENTER);

		sheet.loadBlank();
		sheet.setViewMode(sheet.VIEW_SIMPLE);
		sheet.showSheetTabs(false);
	}

	/** Displays the view */
	public void showView() {
		super.setVisible(true);
		sheet.afterShow();
	}

	/** Returns the spreadsheet of the view */
	public Spreadsheet getSheet() {
		return sheet;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() { // GEN-BEGIN:initComponents
		panel = new javax.swing.JPanel();
		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		helpButton = new javax.swing.JButton();
		jPanel4 = new javax.swing.JPanel();
		jButton4 = new javax.swing.JButton();

		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				closeDialog(evt);
			}
		});

		panel.setLayout(new java.awt.BorderLayout());

		panel.setPreferredSize(new java.awt.Dimension(3, 3));
		getContentPane().add(panel, java.awt.BorderLayout.CENTER);

		jPanel1.setLayout(new java.awt.BorderLayout());

		helpButton.setIcon(ui.getIcon("fina2.help"));
		helpButton.setFont(ui.getFont());
		helpButton.setText(ui.getString("fina2.help"));
		helpButton.setEnabled(false);
		jPanel2.add(helpButton);

		jPanel1.add(jPanel2, java.awt.BorderLayout.WEST);

		jButton4.setIcon(ui.getIcon("fina2.close"));
		jButton4.setFont(ui.getFont());
		jButton4.setText(ui.getString("fina2.close"));
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jPanel4.add(jButton4);

		jPanel1.add(jPanel4, java.awt.BorderLayout.EAST);

		getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

		pack();
	} // GEN-END:initComponents

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) { // GEN-FIRST:event_jButton4ActionPerformed
		sheet.dispose();
		dispose();
	} // GEN-LAST:event_jButton4ActionPerformed

	/** Closes the dialog */
	private void closeDialog(java.awt.event.WindowEvent evt) { // GEN-FIRST:event_closeDialog
		sheet.dispose();
		dispose();
	} // GEN-LAST:event_closeDialog

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JPanel panel;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JButton helpButton;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JButton jButton4;
	// End of variables declaration//GEN-END:variables
}
