DROP SCHEMA IF EXISTS `citius_schema` ;
CREATE SCHEMA IF NOT EXISTS `citius_schema`;
USE `citius_schema` ;

DROP TABLE IF EXISTS `Employee`;
CREATE TABLE citius_schema.Employee (Empid INTEGER NOT NULL,
    Age INTEGER NOT NULL,
    Address VARCHAR(20) NOT NULL,
    PRIMARY KEY (Empid)); 

DROP TABLE IF EXISTS `FORUMS`;
CREATE TABLE citius_schema.FORUMS (FORUM_ID INTEGER NOT NULL,
    FORUM_NAME varchar(20) NOT NULL,
    FORUM_DESC VARCHAR(20) NOT NULL,
    PRIMARY KEY (FORUM_ID)); 

     