//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.17 at 04:43:33 PM GMT+04:00 
//

package fina2.returns.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for HEADER-TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HEADER-TYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BANKCODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BANKNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RETURNCODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RETURNNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PERIODFROM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PERIODEND" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="VER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SIGNED" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LNG" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HEADER-TYPE", propOrder = { "bankcode", "bankname",
        "returncode", "returnname", "periodfrom", "periodend", "ver", "signed",
        "lng" })
public class HEADERTYPE {

    @XmlElement(name = "BANKCODE", required = true)
    protected String bankcode;
    @XmlElement(name = "BANKNAME", required = true)
    protected String bankname;
    @XmlElement(name = "RETURNCODE", required = true)
    protected String returncode;
    @XmlElement(name = "RETURNNAME", required = true)
    protected String returnname;
    @XmlElement(name = "PERIODFROM", required = true)
    protected String periodfrom;
    @XmlElement(name = "PERIODEND", required = true)
    protected String periodend;
    @XmlElement(name = "VER", required = true)
    protected String ver;
    @XmlElement(name = "SIGNED", required = true)
    protected String signed;
    @XmlElement(name = "LNG", required = true)
    protected String lng;

    /**
     * Gets the value of the bankcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBANKCODE() {
        return bankcode;
    }

    /**
     * Sets the value of the bankcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBANKCODE(String value) {
        this.bankcode = value;
    }

    /**
     * Gets the value of the bankname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBANKNAME() {
        return bankname;
    }

    /**
     * Sets the value of the bankname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBANKNAME(String value) {
        this.bankname = value;
    }

    /**
     * Gets the value of the returncode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRETURNCODE() {
        return returncode;
    }

    /**
     * Sets the value of the returncode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRETURNCODE(String value) {
        this.returncode = value;
    }

    /**
     * Gets the value of the returnname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRETURNNAME() {
        return returnname;
    }

    /**
     * Sets the value of the returnname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRETURNNAME(String value) {
        this.returnname = value;
    }

    /**
     * Gets the value of the periodfrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPERIODFROM() {
        return periodfrom;
    }

    /**
     * Sets the value of the periodfrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPERIODFROM(String value) {
        this.periodfrom = value;
    }

    /**
     * Gets the value of the periodend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPERIODEND() {
        return periodend;
    }

    /**
     * Sets the value of the periodend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPERIODEND(String value) {
        this.periodend = value;
    }

    /**
     * Gets the value of the ver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVER() {
        return ver;
    }

    /**
     * Sets the value of the ver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVER(String value) {
        this.ver = value;
    }

    /**
     * Gets the value of the signed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSIGNED() {
        return signed;
    }

    /**
     * Sets the value of the signed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSIGNED(String value) {
        this.signed = value;
    }

    /**
     * Gets the value of the lng property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLNG() {
        return lng;
    }

    /**
     * Sets the value of the lng property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLNG(String value) {
        this.lng = value;
    }

}
