//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.17 at 04:43:33 PM GMT+04:00 
//

package fina2.returns.jaxb;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fina2.returns.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fina2.returns.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HEADERTYPE }
     * 
     */
    public HEADERTYPE createHEADERTYPE() {
        return new HEADERTYPE();
    }

    /**
     * Create an instance of {@link ITEMTYPE }
     * 
     */
    public ITEMTYPE createITEMTYPE() {
        return new ITEMTYPE();
    }

    /**
     * Create an instance of {@link RETURN }
     * 
     */
    public RETURN createRETURN() {
        return new RETURN();
    }

    /**
     * Create an instance of {@link BODYTYPE }
     * 
     */
    public BODYTYPE createBODYTYPE() {
        return new BODYTYPE();
    }

}
