
package fina2.web;

import javax.ejb.*;
import fina2.CodeNotUniqueException ;
import java.rmi.RemoteException;
import java.util.Properties;
import fina2.i18n.Language;
import fina2.bank.LicenceType;
import fina2.bank.BankType;
import fina2.period.PeriodType;
import fina2.returns.ReturnType;
import fina2.returns.Schedule;
import javax.naming.NamingException;
import java.util.Collection; 
import java.util.List; 
/**
 * Created Nov 5, 2003 12:09:51 PM
 * Code generated by the Sun ONE Studio EJB Builder
 * @author zbokuchava
 */

public interface UtilitiesSession extends javax.ejb.EJBObject {
    public void bankGroupAmend(fina2.bank.BankGroup bankGroup, Handle langHandle, String code, String desc)throws RemoteException,fina2.CodeNotUniqueException, javax.transaction.SystemException, fina2.CodeNotUniqueException ;
    public void bankTypeAmend(fina2.bank.BankType bankType, Handle langHandle, String code, String desc) throws javax.transaction.SystemException, fina2.CodeNotUniqueException ;
    public void returnTypeAmend(fina2.returns.ReturnType returnType, Handle langHandle, String code, String desc) throws javax.transaction.SystemException, fina2.CodeNotUniqueException ;
    public void periodTypeAmend(fina2.period.PeriodType periodType, Handle langHandle, String code, String desc) throws javax.transaction.SystemException, fina2.CodeNotUniqueException ;
    public void languageAmend(Language lang, Handle langHandle, String code, String desc, String fontFace,int fontSize, String dateFormat, String numberFormat, String htmlCharset, String xmlEncoding) throws RemoteException, javax.transaction.SystemException, fina2.CodeNotUniqueException ;   
    public void licenseTypeAmend(LicenceType licenseType, Handle langHandle, String  desc) throws RemoteException, javax.transaction.SystemException;   
    public Properties getMessages()throws RemoteException;
    public void setMessages(Properties messages) throws RemoteException;
    public void scheduleAmend(Handle langHandle, int scheduleID, int bankID, int rdID, int periodID, String doa) 
                        throws javax.transaction.SystemException, fina2.CodeNotUniqueException, 
                        NamingException, RemoteException,FinderException, fina2.FinaException, RemoveException;
    public void returnDefinitionAmend(Handle langHandle, int id, String code, String desc, int typeID, Collection tables) 
                        throws javax.transaction.SystemException, fina2.CodeNotUniqueException, 
                        NamingException, RemoteException,FinderException, fina2.FinaException, RemoveException;
    public void periodDefinitionAmend(Handle langHandle, int id, int typeID, String periodNumber, String fromDate, String toDate) 
                        throws javax.transaction.SystemException, fina2.CodeNotUniqueException, 
                        NamingException, RemoteException,FinderException, fina2.FinaException, RemoveException;
    public void test() throws RemoteException;
    //vano
    public void mdtNodeAmend(Handle langHandle,int node,int parent,String code,String description,int type,int evalMethod,
                             boolean required,Collection compRules)
                         throws RemoteException,fina2.FinaException;
    public void mdtInputAmend(Handle langHandle,int node,int parent,String code,String description,int type,
                             boolean required,Collection compRules) throws  RemoteException,fina2.FinaException;    
    public void mdtVariableAmend(Handle langHandle,int node,int parent,String code,String description,String source,List refNodes,
                             boolean required,Collection compRules) throws  RemoteException, fina2.FinaException;
    public void menuAmend(Handle langHandle,int node,int parent,String description) throws RemoteException,RemoveException,FinderException;
    public void menuItemAmend(Handle langHandle,int node,int parent,String description,int type,String action,String app) throws RemoteException,RemoveException,FinderException;     
    public void roleAmend(Handle langHandle,int roleID,String description,Collection permissions) throws RemoteException,fina2.FinaException;
    public void userAmend(Handle langHandle,int userID,String login,String pass,String name,String title,String phone,String email,Collection roles,Collection permissions,Collection banks,Collection reports) throws RemoteException,fina2.FinaException; 

    public void bankAmend(Handle langHandle,Handle userHandle,int bankID,int groupID,String code,String shortName,String swift,String name,String address,String phone,String fax,String email,String telex,int typeID) throws RemoteException,FinderException,CodeNotUniqueException,RemoveException;
    public void licenseAmend(Handle langHandle,int bankID,int licenseID,int typeID,String code,String ldate,String lcdate,String reason,boolean oper) throws RemoteException,FinderException,RemoveException;
    public void bankManagAmend(Handle langHandle,int bankID,int managID,int managBodyID,String name,String lastName,String post,String phone,String appdate,String candate,String regform1,String regform2,String regform3,String comment1,String comment2) throws RemoteException,FinderException,RemoveException;
    public void branchAmend(Handle langHandle,int bankID,int branchID,int regionID,String branchName,String shortName,String branchAddress,String estdate,String candate,String comment)  throws RemoteException,FinderException,RemoveException;
    public void branchManagAmend(Handle langHandle,int bankID,int managID,int managBodyID,String name,String lastName,String post,String phone,String appdate,String candate,String regform1,String regform2,String regform3,String comment1,String comment2) throws RemoteException,FinderException,RemoveException;    
    //end vano 
}

